import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Container, Text } from '@chakra-ui/react';
import Demo from '../components/Demo/Demo';
import { useAccount } from 'wagmi';

const Home: NextPage = () => {
  const { isConnected } = useAccount();

  return (
    <div className={styles.container}>
      <Head>
        <title>Token page demo</title>
        <meta
          content='Generated by @rainbow-me/create-rainbowkit'
          name='description'
        />
        <link href='/favicon.ico' rel='icon' />
      </Head>

      <main className={styles.main}>
        <header className='flex justify-between py-3'>
          <Text fontSize='3xl'>Collab/Land Gated website demo</Text>
          <div className='ml-auto'>
            <ConnectButton />
          </div>
        </header>
        <div className='py-3'>
          <Container maxW='xl' rounded='md'>
            {isConnected ? (
              <>
                <Text fontSize='3xl'>Fill the form below!</Text>
                <Demo />
              </>
            ) : (
              <Text fontSize='3xl'>Please connect your wallet</Text>
            )}
          </Container>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://www.raidguild.org/'
          rel='noopener noreferrer'
          target='_blank'
        >
          Made with ❤️ by your frens at Raid Guild
        </a>
      </footer>
    </div>
  );
};

export default Home;
